version: '2'

services:
  shadowsocks:
    container_name: shadowsocks-libev
    network_mode: "host"
    restart: always
    build:
      context: ./shadowsocks
      dockerfile: Dockerfile.shadowsocks-libev
      # args:
      #   - SS_VER=3.0.6
    image: colachen/shadowsocks-libev:20170519
    volumes:
      - ./shadowsocks:/shadowsocks
    ports:
      - 8388:8388

  kcptun:
    container_name: kcptun
    network_mode: "host"
    restart: always
    build:
      context: ./kcptun
      dockerfile: Dockerfile.kcptun
      # args:
      #  - KCP_VER=20170329      
    image: colachen/kcptun:20170519
    volumes:
      - ./kcptun:/kcptun
    ports:
      - 4000:4000/udp
    depends_on:
      - shadowsocks