version: '2'

services:
  radius:
    build:
      context: .
    image: colachen/freeradius-rpi
    container_name: radius-server
    command: "/usr/sbin/radiusd -X"
    volumes:
      - ${PWD}/config/raddb:/etc/raddb
    ports:
      - "1812:1812"
    command: "/usr/sbin/radiusd -X"
  
  mysql:
    image: hypriot/rpi-mysql:5.5
    container_name: mysql
    restart: always
    volumes:
      - ${PWD}/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=ABCD1234_
      - MYSQL_USER=radius
      - MYSQL_PASSWORD=abcd1234_
      
