version: '2'

services:
  kcp:
    container_name: kcp-client-rpi
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.kcptun-rpi
    image: colachen/rpi-kcp-client:20170520
    volumes:
      - ./config:/kcptun
    ports:
      - 2000:2000