version: '2'

services:
  radius:
    build:
      context: .
    image: colachen/freeradius-rpi
    container_name: radius-server
    command: "/usr/sbin/radiusd -X"
    volumes:
      - ${PWD}/config/raddb/radiusd.conf:/etc/raddb/radiusd.conf
      - ${PWD}/config/raddb/sql:/etc/raddb/mods-available/sql
    links:
      - "mysql"
    ports:
      - "1812:1812"
    command: "/usr/sbin/radiusd -X"
  
  mysql:
    image: hypriot/rpi-mysql:5.5
    container_name: mysql
    restart: always
    volumes:
      - ${PWD}/mysql/data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=abcd1234_
      - MYSQL_DATABASE=radius
      - MYSQL_USER=radius
      - MYSQL_PASSWORD=radius123_
