version: '2'

services:
  kcp:
    container_name: kcptun-rpi
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.kcptun-rpi
    network_mode: "host"
    image: colachen/kcptun-rpi:20170520
    volumes:
      - ./config:/kcptun
    ports:
      - 2000:2000/udp